[default]
src = 'contracts'
out = 'out'
libs = ['lib']
remappings = [
  'ds-test/=lib/ds-test/src/',
  '@ensdomains/=node_modules/@ensdomains/',
  '@openzeppelin/=node_modules/@openzeppelin/',
  '@chainlink/=node_modules/@chainlink/',
  'hardhat/=node_modules/hardhat/'
]
solc_version = '0.8.10'
# See more config options https://github.com/gakonst/foundry/tree/master/config
block_number = 120000
block_timestamp = 1640000000
gas_limit = 9223372036854775807                               # the gas limit in tests
