/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPriceOracleV2Ext,
  IPriceOracleV2ExtInterface,
} from "../../../../contracts/interfaces/IPriceOracle.sol/IPriceOracleV2Ext";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "priceFeed",
        type: "address",
      },
    ],
    name: "addPriceFeed",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IPriceOracleV2Ext__factory {
  static readonly abi = _abi;
  static createInterface(): IPriceOracleV2ExtInterface {
    return new utils.Interface(_abi) as IPriceOracleV2ExtInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPriceOracleV2Ext {
    return new Contract(address, _abi, signerOrProvider) as IPriceOracleV2Ext;
  }
}
