/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iAddressProviderSol from "./IAddressProvider.sol";
export type { iAddressProviderSol };
import type * as iCreditFacadeSol from "./ICreditFacade.sol";
export type { iCreditFacadeSol };
import type * as iCreditManagerV2Sol from "./ICreditManagerV2.sol";
export type { iCreditManagerV2Sol };
import type * as iDataCompressorSol from "./IDataCompressor.sol";
export type { iDataCompressorSol };
import type * as iPriceOracleSol from "./IPriceOracle.sol";
export type { iPriceOracleSol };
export type { ICreditAccount } from "./ICreditAccount";
export type { IVersion } from "./IVersion";
export type { IWETHGateway } from "./IWETHGateway";
